onlyBuiltDependencies:
  - '@robinbobin/eslint-config'
  - '@robinbobin/eslint-config-react'
  - '@robinbobin/eslint-config-react-native'
  - '@robinbobin/prettier-config'
  - '@robinbobin/ts-config'
  - unrs-resolver
